name = "gaga-cockpit-api"
main = "src/index.js"
compatibility_date = "2026-06-02"

[vars]
ENVIRONMENT = "development"

[env.staging]
name = "gaga-cockpit-api-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

[env.production]
name = "gaga-cockpit-api"

[env.production.vars]
ENVIRONMENT = "production"
